-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.analysis_results
(
    id serial NOT NULL,
    data_entry_id integer NOT NULL,
    result_value double precision NOT NULL,
    date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT analysis_results_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.data_entries
(
    id serial NOT NULL,
    feature_1 double precision NOT NULL,
    feature_2 double precision NOT NULL,
    feature_3 double precision NOT NULL,
    date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT data_entries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.model_training
(
    id serial NOT NULL,
    model_name text COLLATE pg_catalog."default" NOT NULL,
    training_accuracy double precision NOT NULL,
    date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT model_training_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.analysis_results
    ADD CONSTRAINT analysis_data_entry_id_fkey FOREIGN KEY (data_entry_id)
    REFERENCES public.data_entries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;